### ISSUE TITLE
Crash when restore is set to 1 to 127

### ISSUE THREAD

**Issue by Reel-Deal** [pinterf/MosquitoNR#1]
Hi there Pinterf, I know you mentioned you're extra busy these days. I'm just reporting this bug: https://forum.doom9.org/showthread.php?p=1968083#post1968083 for whenever you have some free time again.

**Comment by pinterf** [comment]
Thanks, (did not follow doom9).

**Comment by pinterf** [comment]
Yep, something, somewhere is overwriting memory, I cought the issue in the debugger only one in six runs but do not understand yet what happens.

**Comment by Reel-Deal** [comment]
Thanks! That fixed the issue.
